// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: messages.proto

package messages

import (
	actor "github.com/asynkron/protoactor-go/actor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// this is the message the actor on node 1 will send to the remote actor on node 2
type Echo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender  *actor.PID `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"` // this is the PID the remote actor should reply to
	Message string     `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Echo) Reset() {
	*x = Echo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Echo) GetSender() *actor.PID {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Echo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// this is the message the remote actor should reply with
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SomeValue string `protobuf:"bytes,1,opt,name=SomeValue,proto3" json:"SomeValue,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetSomeValue() string {
	if x != nil {
		return x.SomeValue
	}
	return ""
}

type FloatArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Column []float64 `protobuf:"fixed64,1,rep,packed,name=column,proto3" json:"column,omitempty"`
}

func (x *FloatArray) Reset() {
	*x = FloatArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatArray) ProtoMessage() {}

func (x *FloatArray) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatArray.ProtoReflect.Descriptor instead.
func (*FloatArray) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *FloatArray) GetColumn() []float64 {
	if x != nil {
		return x.Column
	}
	return nil
}

type TrainerWeightsMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NizFloatova string        `protobuf:"bytes,1,opt,name=NizFloatova,proto3" json:"NizFloatova,omitempty"`
	WeightsIH   []*FloatArray `protobuf:"bytes,2,rep,name=weightsIH,proto3" json:"weightsIH,omitempty"`
	WeightsHH   []*FloatArray `protobuf:"bytes,3,rep,name=weightsHH,proto3" json:"weightsHH,omitempty"`
	WeightsHO   []*FloatArray `protobuf:"bytes,4,rep,name=weightsHO,proto3" json:"weightsHO,omitempty"`
	BiasH       []float64     `protobuf:"fixed64,5,rep,packed,name=biasH,proto3" json:"biasH,omitempty"`
	BiasH2      []float64     `protobuf:"fixed64,6,rep,packed,name=biasH2,proto3" json:"biasH2,omitempty"`
	BiasO       []float64     `protobuf:"fixed64,7,rep,packed,name=biasO,proto3" json:"biasO,omitempty"`
}

func (x *TrainerWeightsMessage) Reset() {
	*x = TrainerWeightsMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainerWeightsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainerWeightsMessage) ProtoMessage() {}

func (x *TrainerWeightsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainerWeightsMessage.ProtoReflect.Descriptor instead.
func (*TrainerWeightsMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *TrainerWeightsMessage) GetNizFloatova() string {
	if x != nil {
		return x.NizFloatova
	}
	return ""
}

func (x *TrainerWeightsMessage) GetWeightsIH() []*FloatArray {
	if x != nil {
		return x.WeightsIH
	}
	return nil
}

func (x *TrainerWeightsMessage) GetWeightsHH() []*FloatArray {
	if x != nil {
		return x.WeightsHH
	}
	return nil
}

func (x *TrainerWeightsMessage) GetWeightsHO() []*FloatArray {
	if x != nil {
		return x.WeightsHO
	}
	return nil
}

func (x *TrainerWeightsMessage) GetBiasH() []float64 {
	if x != nil {
		return x.BiasH
	}
	return nil
}

func (x *TrainerWeightsMessage) GetBiasH2() []float64 {
	if x != nil {
		return x.BiasH2
	}
	return nil
}

func (x *TrainerWeightsMessage) GetBiasO() []float64 {
	if x != nil {
		return x.BiasO
	}
	return nil
}

type AveragerWeightsMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeightsIH []*FloatArray `protobuf:"bytes,2,rep,name=weightsIH,proto3" json:"weightsIH,omitempty"`
	WeightsHH []*FloatArray `protobuf:"bytes,3,rep,name=weightsHH,proto3" json:"weightsHH,omitempty"`
	WeightsHO []*FloatArray `protobuf:"bytes,4,rep,name=weightsHO,proto3" json:"weightsHO,omitempty"`
	BiasH     []float64     `protobuf:"fixed64,5,rep,packed,name=biasH,proto3" json:"biasH,omitempty"`
	BiasH2    []float64     `protobuf:"fixed64,6,rep,packed,name=biasH2,proto3" json:"biasH2,omitempty"`
	BiasO     []float64     `protobuf:"fixed64,7,rep,packed,name=biasO,proto3" json:"biasO,omitempty"`
}

func (x *AveragerWeightsMessage) Reset() {
	*x = AveragerWeightsMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AveragerWeightsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AveragerWeightsMessage) ProtoMessage() {}

func (x *AveragerWeightsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AveragerWeightsMessage.ProtoReflect.Descriptor instead.
func (*AveragerWeightsMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *AveragerWeightsMessage) GetWeightsIH() []*FloatArray {
	if x != nil {
		return x.WeightsIH
	}
	return nil
}

func (x *AveragerWeightsMessage) GetWeightsHH() []*FloatArray {
	if x != nil {
		return x.WeightsHH
	}
	return nil
}

func (x *AveragerWeightsMessage) GetWeightsHO() []*FloatArray {
	if x != nil {
		return x.WeightsHO
	}
	return nil
}

func (x *AveragerWeightsMessage) GetBiasH() []float64 {
	if x != nil {
		return x.BiasH
	}
	return nil
}

func (x *AveragerWeightsMessage) GetBiasH2() []float64 {
	if x != nil {
		return x.BiasH2
	}
	return nil
}

func (x *AveragerWeightsMessage) GetBiasO() []float64 {
	if x != nil {
		return x.BiasO
	}
	return nil
}

type InterInterfaceWeightsMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeightsIH []*FloatArray `protobuf:"bytes,2,rep,name=weightsIH,proto3" json:"weightsIH,omitempty"`
	WeightsHH []*FloatArray `protobuf:"bytes,3,rep,name=weightsHH,proto3" json:"weightsHH,omitempty"`
	WeightsHO []*FloatArray `protobuf:"bytes,4,rep,name=weightsHO,proto3" json:"weightsHO,omitempty"`
	BiasH     []float64     `protobuf:"fixed64,5,rep,packed,name=biasH,proto3" json:"biasH,omitempty"`
	BiasH2    []float64     `protobuf:"fixed64,6,rep,packed,name=biasH2,proto3" json:"biasH2,omitempty"`
	BiasO     []float64     `protobuf:"fixed64,7,rep,packed,name=biasO,proto3" json:"biasO,omitempty"`
}

func (x *InterInterfaceWeightsMessage) Reset() {
	*x = InterInterfaceWeightsMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterInterfaceWeightsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterInterfaceWeightsMessage) ProtoMessage() {}

func (x *InterInterfaceWeightsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterInterfaceWeightsMessage.ProtoReflect.Descriptor instead.
func (*InterInterfaceWeightsMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *InterInterfaceWeightsMessage) GetWeightsIH() []*FloatArray {
	if x != nil {
		return x.WeightsIH
	}
	return nil
}

func (x *InterInterfaceWeightsMessage) GetWeightsHH() []*FloatArray {
	if x != nil {
		return x.WeightsHH
	}
	return nil
}

func (x *InterInterfaceWeightsMessage) GetWeightsHO() []*FloatArray {
	if x != nil {
		return x.WeightsHO
	}
	return nil
}

func (x *InterInterfaceWeightsMessage) GetBiasH() []float64 {
	if x != nil {
		return x.BiasH
	}
	return nil
}

func (x *InterInterfaceWeightsMessage) GetBiasH2() []float64 {
	if x != nil {
		return x.BiasH2
	}
	return nil
}

func (x *InterInterfaceWeightsMessage) GetBiasO() []float64 {
	if x != nil {
		return x.BiasO
	}
	return nil
}

type InterfaceToAveragerWeightsMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeightsIH []*FloatArray `protobuf:"bytes,2,rep,name=weightsIH,proto3" json:"weightsIH,omitempty"`
	WeightsHH []*FloatArray `protobuf:"bytes,3,rep,name=weightsHH,proto3" json:"weightsHH,omitempty"`
	WeightsHO []*FloatArray `protobuf:"bytes,4,rep,name=weightsHO,proto3" json:"weightsHO,omitempty"`
	BiasH     []float64     `protobuf:"fixed64,5,rep,packed,name=biasH,proto3" json:"biasH,omitempty"`
	BiasH2    []float64     `protobuf:"fixed64,6,rep,packed,name=biasH2,proto3" json:"biasH2,omitempty"`
	BiasO     []float64     `protobuf:"fixed64,7,rep,packed,name=biasO,proto3" json:"biasO,omitempty"`
}

func (x *InterfaceToAveragerWeightsMessage) Reset() {
	*x = InterfaceToAveragerWeightsMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterfaceToAveragerWeightsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceToAveragerWeightsMessage) ProtoMessage() {}

func (x *InterfaceToAveragerWeightsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceToAveragerWeightsMessage.ProtoReflect.Descriptor instead.
func (*InterfaceToAveragerWeightsMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *InterfaceToAveragerWeightsMessage) GetWeightsIH() []*FloatArray {
	if x != nil {
		return x.WeightsIH
	}
	return nil
}

func (x *InterfaceToAveragerWeightsMessage) GetWeightsHH() []*FloatArray {
	if x != nil {
		return x.WeightsHH
	}
	return nil
}

func (x *InterfaceToAveragerWeightsMessage) GetWeightsHO() []*FloatArray {
	if x != nil {
		return x.WeightsHO
	}
	return nil
}

func (x *InterfaceToAveragerWeightsMessage) GetBiasH() []float64 {
	if x != nil {
		return x.BiasH
	}
	return nil
}

func (x *InterfaceToAveragerWeightsMessage) GetBiasH2() []float64 {
	if x != nil {
		return x.BiasH2
	}
	return nil
}

func (x *InterfaceToAveragerWeightsMessage) GetBiasO() []float64 {
	if x != nil {
		return x.BiasO
	}
	return nil
}

type RemoteIntegerPID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YourInterfacePid *actor.PID   `protobuf:"bytes,1,opt,name=yourInterfacePid,proto3" json:"yourInterfacePid,omitempty"`
	AllInterfacePids []*actor.PID `protobuf:"bytes,2,rep,name=allInterfacePids,proto3" json:"allInterfacePids,omitempty"`
}

func (x *RemoteIntegerPID) Reset() {
	*x = RemoteIntegerPID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteIntegerPID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteIntegerPID) ProtoMessage() {}

func (x *RemoteIntegerPID) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteIntegerPID.ProtoReflect.Descriptor instead.
func (*RemoteIntegerPID) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *RemoteIntegerPID) GetYourInterfacePid() *actor.PID {
	if x != nil {
		return x.YourInterfacePid
	}
	return nil
}

func (x *RemoteIntegerPID) GetAllInterfacePids() []*actor.PID {
	if x != nil {
		return x.AllInterfacePids
	}
	return nil
}

type SpawnedAveragerPID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThePid   *actor.PID `protobuf:"bytes,1,opt,name=thePid,proto3" json:"thePid,omitempty"`
	DataPath string     `protobuf:"bytes,2,opt,name=dataPath,proto3" json:"dataPath,omitempty"`
}

func (x *SpawnedAveragerPID) Reset() {
	*x = SpawnedAveragerPID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnedAveragerPID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnedAveragerPID) ProtoMessage() {}

func (x *SpawnedAveragerPID) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnedAveragerPID.ProtoReflect.Descriptor instead.
func (*SpawnedAveragerPID) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *SpawnedAveragerPID) GetThePid() *actor.PID {
	if x != nil {
		return x.ThePid
	}
	return nil
}

func (x *SpawnedAveragerPID) GetDataPath() string {
	if x != nil {
		return x.DataPath
	}
	return ""
}

type SpawnedTrainerPID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThePid *actor.PID `protobuf:"bytes,1,opt,name=thePid,proto3" json:"thePid,omitempty"`
}

func (x *SpawnedTrainerPID) Reset() {
	*x = SpawnedTrainerPID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnedTrainerPID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnedTrainerPID) ProtoMessage() {}

func (x *SpawnedTrainerPID) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnedTrainerPID.ProtoReflect.Descriptor instead.
func (*SpawnedTrainerPID) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *SpawnedTrainerPID) GetThePid() *actor.PID {
	if x != nil {
		return x.ThePid
	}
	return nil
}

type SpawnedInterfacePID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThePid *actor.PID `protobuf:"bytes,1,opt,name=thePid,proto3" json:"thePid,omitempty"`
}

func (x *SpawnedInterfacePID) Reset() {
	*x = SpawnedInterfacePID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnedInterfacePID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnedInterfacePID) ProtoMessage() {}

func (x *SpawnedInterfacePID) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnedInterfacePID.ProtoReflect.Descriptor instead.
func (*SpawnedInterfacePID) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *SpawnedInterfacePID) GetThePid() *actor.PID {
	if x != nil {
		return x.ThePid
	}
	return nil
}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x0b, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12,
	0x22, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x06, 0x53, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x28, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x6f, 0x6d,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x6f,
	0x6d, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x24, 0x0a, 0x0a, 0x46, 0x6c, 0x6f, 0x61, 0x74,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x99, 0x02,
	0x0a, 0x15, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x69, 0x7a, 0x46, 0x6c,
	0x6f, 0x61, 0x74, 0x6f, 0x76, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4e, 0x69,
	0x7a, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x6f, 0x76, 0x61, 0x12, 0x32, 0x0a, 0x09, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x49, 0x48, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x41, 0x72, 0x72,
	0x61, 0x79, 0x52, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x49, 0x48, 0x12, 0x32, 0x0a,
	0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x48, 0x48, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x6c, 0x6f, 0x61,
	0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x48,
	0x48, 0x12, 0x32, 0x0a, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x48, 0x4f, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x46, 0x6c, 0x6f, 0x61, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x09, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x48, 0x4f, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x69, 0x61, 0x73, 0x48, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x05, 0x62, 0x69, 0x61, 0x73, 0x48, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x69, 0x61, 0x73, 0x48, 0x32, 0x18, 0x06, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x62, 0x69, 0x61,
	0x73, 0x48, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x69, 0x61, 0x73, 0x4f, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x01, 0x52, 0x05, 0x62, 0x69, 0x61, 0x73, 0x4f, 0x22, 0xf8, 0x01, 0x0a, 0x16, 0x41, 0x76,
	0x65, 0x72, 0x61, 0x67, 0x65, 0x72, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x49,
	0x48, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x09, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x49, 0x48, 0x12, 0x32, 0x0a, 0x09, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x48, 0x48, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x52, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x48, 0x48, 0x12, 0x32, 0x0a, 0x09,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x48, 0x4f, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x48, 0x4f,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x69, 0x61, 0x73, 0x48, 0x18, 0x05, 0x20, 0x03, 0x28, 0x01, 0x52,
	0x05, 0x62, 0x69, 0x61, 0x73, 0x48, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x61, 0x73, 0x48, 0x32,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x62, 0x69, 0x61, 0x73, 0x48, 0x32, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x69, 0x61, 0x73, 0x4f, 0x18, 0x07, 0x20, 0x03, 0x28, 0x01, 0x52, 0x05, 0x62,
	0x69, 0x61, 0x73, 0x4f, 0x22, 0xfe, 0x01, 0x0a, 0x1c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x49, 0x48, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x09,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x49, 0x48, 0x12, 0x32, 0x0a, 0x09, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x48, 0x48, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x41, 0x72, 0x72,
	0x61, 0x79, 0x52, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x48, 0x48, 0x12, 0x32, 0x0a,
	0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x48, 0x4f, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x6c, 0x6f, 0x61,
	0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x48,
	0x4f, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x69, 0x61, 0x73, 0x48, 0x18, 0x05, 0x20, 0x03, 0x28, 0x01,
	0x52, 0x05, 0x62, 0x69, 0x61, 0x73, 0x48, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x61, 0x73, 0x48,
	0x32, 0x18, 0x06, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x62, 0x69, 0x61, 0x73, 0x48, 0x32, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x69, 0x61, 0x73, 0x4f, 0x18, 0x07, 0x20, 0x03, 0x28, 0x01, 0x52, 0x05,
	0x62, 0x69, 0x61, 0x73, 0x4f, 0x22, 0x83, 0x02, 0x0a, 0x21, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x54, 0x6f, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x72, 0x57, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x49, 0x48, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x52, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x49, 0x48, 0x12,
	0x32, 0x0a, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x48, 0x48, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x6c,
	0x6f, 0x61, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x48, 0x48, 0x12, 0x32, 0x0a, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x48, 0x4f,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x09, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x48, 0x4f, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x69, 0x61, 0x73, 0x48,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x01, 0x52, 0x05, 0x62, 0x69, 0x61, 0x73, 0x48, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x69, 0x61, 0x73, 0x48, 0x32, 0x18, 0x06, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x62,
	0x69, 0x61, 0x73, 0x48, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x69, 0x61, 0x73, 0x4f, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x05, 0x62, 0x69, 0x61, 0x73, 0x4f, 0x22, 0x82, 0x01, 0x0a, 0x10,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x50, 0x49, 0x44,
	0x12, 0x36, 0x0a, 0x10, 0x79, 0x6f, 0x75, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x50, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x10, 0x79, 0x6f, 0x75, 0x72, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x50, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x10, 0x61, 0x6c, 0x6c, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x50, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x10,
	0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x50, 0x69, 0x64, 0x73,
	0x22, 0x54, 0x0a, 0x12, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x65, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x72, 0x50, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x06, 0x74, 0x68, 0x65, 0x50, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50,
	0x49, 0x44, 0x52, 0x06, 0x74, 0x68, 0x65, 0x50, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x50, 0x61, 0x74, 0x68, 0x22, 0x37, 0x0a, 0x11, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x65,
	0x64, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x50, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x06, 0x74,
	0x68, 0x65, 0x50, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x06, 0x74, 0x68, 0x65, 0x50, 0x69, 0x64, 0x22,
	0x39, 0x0a, 0x13, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x50, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x06, 0x74, 0x68, 0x65, 0x50, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50,
	0x49, 0x44, 0x52, 0x06, 0x74, 0x68, 0x65, 0x50, 0x69, 0x64, 0x42, 0x11, 0x5a, 0x0f, 0x76, 0x65,
	0x7a, 0x62, 0x65, 0x33, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_messages_proto_goTypes = []interface{}{
	(*Echo)(nil),                              // 0: messages.Echo
	(*Response)(nil),                          // 1: messages.Response
	(*FloatArray)(nil),                        // 2: messages.FloatArray
	(*TrainerWeightsMessage)(nil),             // 3: messages.TrainerWeightsMessage
	(*AveragerWeightsMessage)(nil),            // 4: messages.AveragerWeightsMessage
	(*InterInterfaceWeightsMessage)(nil),      // 5: messages.InterInterfaceWeightsMessage
	(*InterfaceToAveragerWeightsMessage)(nil), // 6: messages.InterfaceToAveragerWeightsMessage
	(*RemoteIntegerPID)(nil),                  // 7: messages.RemoteIntegerPID
	(*SpawnedAveragerPID)(nil),                // 8: messages.SpawnedAveragerPID
	(*SpawnedTrainerPID)(nil),                 // 9: messages.SpawnedTrainerPID
	(*SpawnedInterfacePID)(nil),               // 10: messages.SpawnedInterfacePID
	(*actor.PID)(nil),                         // 11: actor.PID
}
var file_messages_proto_depIdxs = []int32{
	11, // 0: messages.Echo.Sender:type_name -> actor.PID
	2,  // 1: messages.TrainerWeightsMessage.weightsIH:type_name -> messages.FloatArray
	2,  // 2: messages.TrainerWeightsMessage.weightsHH:type_name -> messages.FloatArray
	2,  // 3: messages.TrainerWeightsMessage.weightsHO:type_name -> messages.FloatArray
	2,  // 4: messages.AveragerWeightsMessage.weightsIH:type_name -> messages.FloatArray
	2,  // 5: messages.AveragerWeightsMessage.weightsHH:type_name -> messages.FloatArray
	2,  // 6: messages.AveragerWeightsMessage.weightsHO:type_name -> messages.FloatArray
	2,  // 7: messages.InterInterfaceWeightsMessage.weightsIH:type_name -> messages.FloatArray
	2,  // 8: messages.InterInterfaceWeightsMessage.weightsHH:type_name -> messages.FloatArray
	2,  // 9: messages.InterInterfaceWeightsMessage.weightsHO:type_name -> messages.FloatArray
	2,  // 10: messages.InterfaceToAveragerWeightsMessage.weightsIH:type_name -> messages.FloatArray
	2,  // 11: messages.InterfaceToAveragerWeightsMessage.weightsHH:type_name -> messages.FloatArray
	2,  // 12: messages.InterfaceToAveragerWeightsMessage.weightsHO:type_name -> messages.FloatArray
	11, // 13: messages.RemoteIntegerPID.yourInterfacePid:type_name -> actor.PID
	11, // 14: messages.RemoteIntegerPID.allInterfacePids:type_name -> actor.PID
	11, // 15: messages.SpawnedAveragerPID.thePid:type_name -> actor.PID
	11, // 16: messages.SpawnedTrainerPID.thePid:type_name -> actor.PID
	11, // 17: messages.SpawnedInterfacePID.thePid:type_name -> actor.PID
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Echo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainerWeightsMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AveragerWeightsMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterInterfaceWeightsMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterfaceToAveragerWeightsMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteIntegerPID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnedAveragerPID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnedTrainerPID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnedInterfacePID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
